### PR TITLE
Compendium Browser - Pokémon Tab - New Filters for Abilities, Moves and Capabilities

### PR DESCRIPTION
**Pull request by Tinkastrong**
- Features
   - Types Sorted Alphabetically
   - New Filters for Abilities and Moves
     - Moves can come from any list of levelUp, egg, tutor, machine
     - Abilities can come from any rank of basic, advanced, high
    - All movement capabilities (except Teleport) now can be filtered by
    - The ranges use the minimum and maximum of all loaded species
 - Tech
   - Check via Name Slug for both Abilities and Moves
   - Abilities and Moves expose their IndexFields that are used the the pack Loader. As the PackLoader caches the results, of the Abilties/Moves are loaded from the Species Tab, they still need all of their data. Otherwise, switching from Species to Moves/Abilities breaks the Moves/Abilities Tab in the Compendium Browser.
   - When loading Abilities/Moves in the Species tab, it uses `loadPacks(documentType, packs, indexFields)` with the packs for Moves/Abilities tabs, not Species. (see Cross-Tab Pack selection below) 
    - Sliders now work
      - Added noUiSlider v15.7.1
        - `nouislider.css`, `nouislider.mjs`
      - attempted to work as similar to how Tagify is added to PTR as I am able to
      - PF2e had an extra .scss file for some slider styles that are very much needed - min/max labels were otherwise misplaced. I had no idea what to properly do with that, so I converted it into an extra css file, `slider.css`
      - Made sliders visible per default, as otherwise you would have to click twice on a Sliderfilter to open it, it would auto close and also scroll on the y axis when ever anything is updated. Could not create any weird behavior now that it is visible by default.
    - Compiled `main.less` with latest `lessc` vom `npm`. Hope that's correct. The diff looks good.

---

### First part - Ability and Move Filters (old recording missing capability sliders)

[Screencast from 2023-10-28 16-40-56.webm](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/149251521/4dcb0c1e-9a5c-4555-b2ec-787323909739)

### Second part - with Capability Sliders

[Screencast from 2023-10-30 03-11-47.webm](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/149251521/78351df3-12bf-42aa-ae93-721a26eb097f)

---

### Cross-Tab Pack selection

*For easier readability, this only talks about moves, but is applicable to abilities as well*

image

The design question at hand is "from which packs do you load moves to offer as filter for species?" The solution implemented in works as follows: 
- The moves offered in the species tab are identical to those offered in the moves tab
- The settings tab only lists packs containing species for the species tab, the moves settings only packs with moves  
- Changing the settings for the moves tab in the settings tab changes the moves offered in the species tab
- Once Moves are loaded from either the Moves or Species tab, they are cached and do not need to be loaded again (more needed to be done to archive this, not only the decision on pack selection)

Another option would be to add sub-settings for the species tab to select which packs it should load moves from. A high efficiency:tm: mock up can be seen in a mock up.

image

---

### CODE REVIEW

**Comment by Tinkastrong** [comment]
Upated PR to more Features. Now includes functional Sliders in CompendiumBrowser and Capability Filters for Species

**Comment by dylanpiera** [comment]
Planning on releasing 4.0 either alongside Beta 16 or soon after, gonna have to delay this till the version after as it requires an extensive review.

**Comment by Tinkastrong** [comment]
Working on properly decoupling the tabs.

**Comment by Tinkastrong** [comment]
opened new PR #538 because of Git Skill issue <.<

**Pull request closed without merging**
