### PR TITLE
Poke nav tab

### PR DESCRIPTION
**Pull request by Ellamental2**
taking inspiration from [Amarulence's Poketalk](https://github.com/DarkSerpent/PokeTalk), i'm trying to make a Pokenav tab (can be turned off in the options) which will contain "contacts" that players can use to make notes on NPCs.

this will work similarly to the dex tab

TODO:
- [X]  Add Pokenav tab to charactersheet
- [X] ~~Add game setting to turn pokenav tab off]~~
- [x] Add contact Item
- [x] make item-contact-sheet
- [x] make tab show a list of contacts and the notes they have on each contact
- [x] "sort alphabetically" button
- [x] search bar
- [ ] maybe make it look like a mobile phone like the origonal poketalk?
- [x] add tab button "add contact" which takes a targeted actor and adds them to the list.
- [x] add right click option on actors in the foundry side bar to "create contact item" for GMs to then drag onto characters sheets

### CODE REVIEW

**Comment by dylanpiera** [comment]
additional feature ideas:
- [ ] Add message log / status history for Contacts
- [ ] Add item syncrhonization between GM and all players that share the contact item

**Comment by Ellamental2** [comment]
> additional feature ideas:
> 
> - Add message log / status history for Contacts
> 
> - Add item syncrhonization between GM and all players that share the contact item

Will probably need help with the syncing as it's not something I've done before

**Comment by Ellamental2** [comment]
I can't decide whether to have the smartphone frame.... it's a cool idea but i don't know if it fits with the rest of the sheet... thoughts?

**Comment by Ellamental2** [comment]
Managed to get a working searchbar

image

image

image

**Comment by Ellamental2** [comment]
option for GMs to right click on an actor and create a contact for that actor added. This will create the contact using the Title and Image of the actor in the sidebar.

<details>
<summary> Example </summary>

image

image

</details>

**Comment by Ellamental2** [comment]
added a create actor button within the actor sheet, only visible to GMs

image

**Pull request closed without merging**
