### PR TITLE
New Settings for Injuries

### PR DESCRIPTION
**Pull request by Tinkastrong**
The Injury Rules state themselves that they depend on the style of game you want to play. In the beta, there is no customization for those rules possible. This would also allow in the context of the Book of the Divine to enable the War Aura that states thresholds to become 25% during the fight. 

- New PTR Settings for customizing Injury Rules
  - This does not effect Injuries through Boss HP bars.
  - Edit the fraction of max HP of an actor that counts as Massive Damage (default 50%)
  - Edit the interval at which, down from 100% HP, injuries are applied (default 50%, resulting to Injuries at 50%, 0%, -50%, ...)
  - Accepts 
    - ~~decimal notation - `0.35` for 35%~~
    - ~~fractions - `1/3` for 33.333333333333%~~
    - Percentages in decimal notation.
  - Rejects saving setting if input is invalid
  - Allows you to practically disable mechanics by setting very large values, like `10000`. If you deal 10.000% max HP damage, Injuries should not be a concern...
- Tech
  - ~~To allow fractions like `1/3`, I decided to use a text input field. This fields value gets converted to a number via `Roll.safeEval()`.~~
  - ~~No invalid setting should be saved as input validity is checked for before saving~~

[Screencast from 2023-11-03 12-22-16.webm](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/149251521/2055f444-2590-41d7-88b2-fed2cd9c2e35)

[Screencast from 2023-11-03 12-23-34.webm](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/149251521/57b8ff22-5363-4eab-ac29-a0dc3cb6a4f0)

### CODE REVIEW

**Comment by dylanpiera** [comment]
Not a huge fan of storing the formula and having to calculate it every time. Pref. we actually store the end result instead

**Comment by Tinkastrong** [comment]
Totally understandable. Do you consider it appropriate to store both the final value as well as how it has been input, so that if a user enters `1/3` they to nut get to see `0.3333333333333333`, or is that too little flourish for redundant data?

**Comment by dylanpiera** [comment]
I say don't bother and lets store up to 3 decimal points

**Comment by Tinkastrong** [comment]
Since the value would get truncated either way, a made the inputs simple numbers for percentages like in the GenerationSettings. No need to overcomplicate for barely any benefit.

**Review by dylanpiera — CHANGES_REQUESTED** [review]
There isn't really a reason to have this be its own setting category it fits in `automation`.

Please update it and I'll approve it; or I'll do it myself at a later point since it's only a small fix.

**Comment by Tinkastrong** [comment]
Relocated into Automation.
Could not break in 6 minutes killing a quillfish to -1800% hp

**Pull request merged**
