### PR TITLE
trainer combat

### PR DESCRIPTION
**Pull request by drakodra**
changes:
character-sheet.js:
-changed 'abilities' to 'ability' in the allocating switch so abilities have somewhere to go

character-sheet.hbs
-added abilities to extra tab
-added the moves tab

issues:
-abilities are hugging capabilities
-moves don't roll yet

### CODE REVIEW

**Comment by dylanpiera** [comment]
> issues:
> -abilities are hugging capabilities
> -moves don't roll yet

You can use the  `pt-X` or `pb-X` classes to add some padding to elements. 

f.e. `<div class="pt-2">`

I can fix up rollable moves later, thanks for the work already!

**Comment by drakodra** [comment]
i added the spacing so the abilities don't hug the capabilities anymore

**Review by dylanpiera — APPROVED** [review]
Looks good, will test it in a bit and then merge it into live.

**Comment by dylanpiera** [comment]
Based on the result in the #feedback channel on the Discord Server we might have to end up discarding most of your changes (if we end up updating the Gen4 trainer sheet to Gen8). Either way you find a nice little bug so that'll be incorporated either way :)

**Pull request closed without merging**
